# Generated by Django 5.2.8 on 2025-11-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя ведущего')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Опыт (лет)')),
            ],
            options={
                'verbose_name': 'Ведущий',
                'verbose_name_plural': 'Ведущии',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='День недели')),
                ('order', models.IntegerField(unique=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название трека')),
                ('artist', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Музыкальное произведение',
                'verbose_name_plural': 'Музыкальные произведения',
            },
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.hall', verbose_name='Зал')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.host', verbose_name='Ведущии')),
                ('music_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.musictrack', verbose_name='Музыкальное произведение')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repertoire.weekday', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Репертуар',
                'verbose_name_plural': 'Репертуары',
            },
        ),
    ]
