# Generated by Django 5.2.8 on 2025-11-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='bpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='BPN'),
        ),
    ]
